import {
  SiCplusplus, SiC, SiHtml5, SiCss, SiJavascript, SiTypescript,
  SiReact, SiNextdotjs, SiTailwindcss, SiMaterialdesign,
  SiMui, SiBootstrap, SiSass, SiMysql, SiRedux,
  SiMongodb, SiExpress, SiNodedotjs, SiPython, SiDjango,
  SiFlask, SiPostgresql, SiDocker, SiKubernetes, SiGit,
  SiGithub, SiLinux, SiFigma, SiGraphql, SiFirebase,
  SiRedis, SiJest, SiVuedotjs, SiAngular,
  SiNuxt, SiSvelte, SiWebpack, SiBabel, SiNginx,
  SiApache, SiPhp, SiLaravel, SiRust, SiGo, SiKotlin,
  SiSwift, SiFlutter, SiTerraform, SiAnsible, SiJenkins,
} from "react-icons/si";
import { IconType } from "react-icons";

export const iconRegistry: Record<string, IconType> = {
  "C++": SiCplusplus,
  "C": SiC,
  "HTML5": SiHtml5,
  "CSS3": SiCss,
  "JavaScript": SiJavascript,
  "TypeScript": SiTypescript,
  "React": SiReact,
  "Next.js": SiNextdotjs,
  "Tailwind CSS": SiTailwindcss,
  "Material Design": SiMaterialdesign,
  "MUI": SiMui,
  "Bootstrap": SiBootstrap,
  "Sass": SiSass,
  "MySQL": SiMysql,
  "Redux": SiRedux,
  "MongoDB": SiMongodb,
  "Express": SiExpress,
  "Node.js": SiNodedotjs,
  "Python": SiPython,
  "Django": SiDjango,
  "Flask": SiFlask,
  "PostgreSQL": SiPostgresql,
  "Docker": SiDocker,
  "Kubernetes": SiKubernetes,
  "Git": SiGit,
  "GitHub": SiGithub,
  "Linux": SiLinux,
  "Figma": SiFigma,
  "GraphQL": SiGraphql,
  "Firebase": SiFirebase,
  "Redis": SiRedis,
  "Jest": SiJest,
  "Vue.js": SiVuedotjs,
  "Angular": SiAngular,
  "Nuxt.js": SiNuxt,
  "Svelte": SiSvelte,
  "Webpack": SiWebpack,
  "Babel": SiBabel,
  "Nginx": SiNginx,
  "Apache": SiApache,
  "PHP": SiPhp,
  "Laravel": SiLaravel,
  "Rust": SiRust,
  "Go": SiGo,
  "Kotlin": SiKotlin,
  "Swift": SiSwift,
  "Flutter": SiFlutter,
  "Terraform": SiTerraform,
  "Ansible": SiAnsible,
  "Jenkins": SiJenkins,
};

export const iconList = Object.keys(iconRegistry).sort();
