import { IconType } from "react-icons";
import {
  SiReact, SiNextdotjs, SiNodedotjs, SiMongodb, SiExpress, SiTypescript,
  SiJavascript, SiHtml5, SiCss, SiTailwindcss, SiBootstrap, SiRedux,
  SiPython, SiDjango, SiFlask, SiPostgresql, SiMysql, SiFirebase,
  SiDocker, SiKubernetes, SiGit, SiGithub, SiFigma, SiGraphql,
  SiRedis, SiVuedotjs, SiAngular, SiSvelte, SiNuxt, SiPhp, SiLaravel,
  SiRust, SiGo, SiFlutter, SiSwift, SiKotlin, SiMui, SiSass,
  SiWebpack, SiNginx, SiTerraform, SiJenkins, SiJest, SiCypress,
  SiStorybook, SiElectron, SiReactrouter, SiExpo, SiPwa,
  SiChakraui, SiStyledcomponents, SiFramer,
} from "react-icons/si";
import {
  FiGlobe, FiSmartphone, FiMonitor, FiServer, FiCloud, FiDatabase,
  FiCode, FiLayout, FiShoppingCart, FiMail, FiMessageCircle,
  FiBarChart2, FiCamera, FiFilm, FiMusic, FiBook, FiMap, FiCalendar,
  FiUsers, FiSettings, FiShield, FiZap, FiSun, FiMoon, FiStar,
  FiHeart, FiLock, FiUnlock, FiDownload, FiUpload, FiRefreshCw,
  FiSearch, FiMenu, FiGrid, FiList, FiTrello, FiSlack, FiDollarSign,
  FiCreditCard, FiTrendingUp, FiActivity, FiCompass, FiTarget,
  FiBookOpen,
} from "react-icons/fi";
import {
  MdStore, MdRestaurant, MdSchool, MdLocalHospital, MdFlight,
  MdHotel, MdDirectionsCar, MdSportsEsports, MdMovie, MdLibraryMusic,
  MdScience, MdAgriculture, MdRealEstateAgent, MdPets, MdToys,
  MdPalette, MdArchitecture, MdEngineering, MdAnalytics, MdHub,
  MdCloudQueue, MdDevices, MdShare, MdLanguage, MdHandshake,
  MdEmojiEvents, MdRocket, MdLightbulb, MdGroups, MdPublic,
  MdMenuBook, MdLocalLibrary, MdCastForEducation, MdLibraryBooks,
  MdBookOnline, MdBook,
} from "react-icons/md";

export const projectIconRegistry: Record<string, IconType> = {
  // Tech brands (from Si)
  React: SiReact,
  Nextjs: SiNextdotjs,
  Nodejs: SiNodedotjs,
  MongoDB: SiMongodb,
  Express: SiExpress,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  CSS3: SiCss,
  Tailwind: SiTailwindcss,
  Bootstrap: SiBootstrap,
  Redux: SiRedux,
  Python: SiPython,
  Django: SiDjango,
  Flask: SiFlask,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Firebase: SiFirebase,
  Docker: SiDocker,
  Git: SiGit,
  GitHub: SiGithub,
  Figma: SiFigma,
  GraphQL: SiGraphql,
  Redis: SiRedis,
  Vue: SiVuedotjs,
  Angular: SiAngular,
  Svelte: SiSvelte,
  Nuxt: SiNuxt,
  PHP: SiPhp,
  Laravel: SiLaravel,
  Rust: SiRust,
  Go: SiGo,
  Flutter: SiFlutter,
  Swift: SiSwift,
  Kotlin: SiKotlin,
  MUI: SiMui,
  Webpack: SiWebpack,
  Jest: SiJest,
  PWA: SiPwa,
  Electron: SiElectron,
  Framer: SiFramer,
  Expo: SiExpo,
  // General/UI (from Fi)
  Globe: FiGlobe,
  Smartphone: FiSmartphone,
  Monitor: FiMonitor,
  Server: FiServer,
  Cloud: FiCloud,
  Database: FiDatabase,
  Code: FiCode,
  Layout: FiLayout,
  Cart: FiShoppingCart,
  Mail: FiMail,
  Chat: FiMessageCircle,
  Chart: FiBarChart2,
  Camera: FiCamera,
  Film: FiFilm,
  Music: FiMusic,
  Book: FiBook,
  BookOpen: FiBookOpen,
  MenuBook: MdMenuBook,
  LocalLibrary: MdLocalLibrary,
  LibraryBooks: MdLibraryBooks,
  BookOnline: MdBookOnline,
  BookMd: MdBook,
  CastForEducation: MdCastForEducation,
  Map: FiMap,
  Calendar: FiCalendar,
  Users: FiUsers,
  Settings: FiSettings,
  Shield: FiShield,
  Star: FiStar,
  Heart: FiHeart,
  Target: FiTarget,
  Compass: FiCompass,
  Refresh: FiRefreshCw,
  Search: FiSearch,
  Grid: FiGrid,
  List: FiList,
  Trello: FiTrello,
  Slack: FiSlack,
  Dollar: FiDollarSign,
  CreditCard: FiCreditCard,
  Trending: FiTrendingUp,
  Activity: FiActivity,
  Download: FiDownload,
  Upload: FiUpload,
  // Material Design (from Md)
  Store: MdStore,
  Restaurant: MdRestaurant,
  School: MdSchool,
  Hospital: MdLocalHospital,
  Flight: MdFlight,
  Hotel: MdHotel,
  Car: MdDirectionsCar,
  Gaming: MdSportsEsports,
  Movie: MdMovie,
  Science: MdScience,
  Agriculture: MdAgriculture,
  RealEstate: MdRealEstateAgent,
  Pets: MdPets,
  Toys: MdToys,
  Palette: MdPalette,
  Architecture: MdArchitecture,
  Engineering: MdEngineering,
  Analytics: MdAnalytics,
  Hub: MdHub,
  Devices: MdDevices,
  Share: MdShare,
  Language: MdLanguage,
  Handshake: MdHandshake,
  Trophy: MdEmojiEvents,
  Rocket: MdRocket,
  Lightbulb: MdLightbulb,
  Group: MdGroups,
  Public: MdPublic,
};

export const projectIconList = Object.keys(projectIconRegistry).sort();
